version: "3"

services:
  db:
    image: postgres
    env_file: ./.envs/postgres
    networks: 
      - my-little-office
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-little-office_django
    depends_on:
      - db
    env_file:
      - ./.envs/postgres
      - ./.envs/django
    networks: 
      - my-little-office
    volumes:
      - .:/usr/src/app:z
    ports:
      - "8000:8000"
    command: /usr/src/app/start.sh

  redis:
    image: redis:6.0
    networks: 
      - my-little-office

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-little-office_celery_worker
    depends_on:
      - redis
      - db
    env_file:
      - ./.envs/postgres
      - ./.envs/django
    networks: 
      - my-little-office
    volumes:
      - .:/usr/src/app:z
    command: /usr/src/app/compose/celery_worker.sh
    ports: []

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-little-office_celery_beat
    depends_on:
      - redis
      - db
    env_file:
      - ./.envs/postgres
      - ./.envs/django
    networks: 
      - my-little-office
    volumes:
      - .:/usr/src/app:z
    command: /usr/src/app/compose/celery_beat.sh
    ports: []


volumes:
  postgres_data:

networks: 
  my-little-office:
