# Generated by Django 3.1.5 on 2021-01-12 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210112_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='employment date'),
        ),
    ]
