# Generated by Django 3.1.5 on 2021-01-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210113_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['tree_id', 'lft'], 'permissions': [('can_view_api', 'Can view API')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Staff'},
        ),
    ]
