# Generated by Django 3.1.5 on 2021-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210113_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='patronim',
        ),
        migrations.AddField(
            model_name='employee',
            name='patronym',
            field=models.CharField(blank=True, max_length=150, verbose_name='patronym'),
        ),
    ]
