# Generated by Django 3.1.5 on 2021-01-13 23:29

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask


def add_periodic_task(apps, schema_editor):
    schedule, created = IntervalSchedule.objects.get_or_create(
        every=2,
        period=IntervalSchedule.HOURS,
    )
    PeriodicTask.objects.create(
        interval=schedule,
        name='Accrue salary to all workers',
        task='my_little_office.apps.staff.tasks.accrue_salary'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210113_2259'),
    ]

    operations = [
        migrations.RunPython(add_periodic_task)
    ]
